### ISSUE TITLE
add additional classpath for pyjnius config

### ISSUE THREAD

**Issue by seanmacavaney** [terrier-org/pyterrier#20]
It seems there's an easy way to specify additional jvm options in `pt.init()`, but it may be handy to be able to specify other locations to add to the classpath as well. The use case would be if somebody wants to use both pyterrier and pyjnius to interface with other java libraries.

I'm thinking something like:

```
def init(version=None, mem=None, packages=[], jvm_opts=[], redirect_io=True, logging='WARN', home_dir=None, jvm_classpaths=[]): # adding to end to avoid breaking existing code that may use positional arguments
    ...
    for jar in classpathTrJars:
        jnius_config.add_classpath(jar)
    for jar in jvm_classpaths:
        jnius_config.add_classpath(jar)
                -or-
    jnius_config.add_classpath(*classpathTrJars, *jvm_classpaths)
```

**Comment by cmacdonald** [comment]
Thanks for the feedback. Last night I coincidentally added a `boot_packages=[]` option to `pt.init()` on a local branch, which will add Maven dependencies jar files, so that their classes would be available for  - would this cover your main use case?  You could load anything in your local Maven repo, or on mavencentral.

`pt.init()` doesnt override the classpath or Java commandline options set in jnius, so you can add jnius_config to add extra jar files, by calling `jnius_config.add_classpath()` if the jar file is local but isnt Maven accessible?

**Comment by seanmacavaney** [comment]
Ah, great! These options cover my use cases. The Maven option will be particularly handy, I believe.
