### ISSUE TITLE
How to use customized wmodel?

### ISSUE THREAD

**Issue by ArvinZhuang** [terrier-org/pyterrier#208]
Hi,
Instead of using a predefined wmodel string (e.g., pt.BatchRetrieve(index, wmodel="BM25")), is there any way to pass a customized python wmodel class to BatchRetrieve? Such as pt.BatchRetrieve(index, wmodel=MyPythonWeightingModel). 
Thanks

**Comment by cmacdonald** [comment]
not currently. It something that _could_ be done - we'd need a Java class to act as a proxy WeightingModel, as Python classes cant extend Java classes in PyJnius.

These are three objects typically involved in scoring: the [Posting](http://terrier.org/docs/current/javadoc/org/terrier/structures/postings/Posting.html), the [EntryStatistics](http://terrier.org/docs/current/javadoc/org/terrier/structures/EntryStatistics.html) and the [CollectionStatistics](http://terrier.org/docs/current/javadoc/org/terrier/structures/CollectionStatistics.html).

An API could be something like:
```python
pt.BatchRetrieve(index, wmodel=pt.terrier.wmodel(lambda collStats, entryStats, posting : return posting.getFrequency()) )
```
This example would be equivalent to a `wmodel="Tf"`.  Actually, the pt.terrier.wmodel() bit might not be required - any Callable would be accepted.

Could you provide an example use case - what statistics you need access to etc?

There are a few aspects of this:
 - [ ] changing BatchRetrieve to accept a Terrier Java WeightingModel _instance_ rather than a String.
 - [ ] Any needed changes in Terrier to support this - I actually dont think any are required.
 - [ ] adding a WeightingModel proxy class in terrier-python-helper. I'd need to think more about the exact API.
 - [ ] adding the PyTerrier code to instantiate the WeightingModel proxy.

Is this something that you would be able to help with?

**Comment by ArvinZhuang** [comment]
Hi @cmacdonald ,
We are planning to use pyterrier in our information retrieval course. We would like students to be able to write their own versions of document scoring functions like bm25. Do you know if this is something that is currently possible (i.e., with pipelines) or would we need to make the changes as you have suggested above?

**Comment by cmacdonald** [comment]
Whats your timescale Arvin - i.e. when does your course start? 

What we did in our course was have students do custom re-rankers in Python, eg. URL Length using [pt.apply functions].(https://pyterrier.readthedocs.io/en/latest/apply.html)
We also asked them to, e.g. re-rank TF results by using TF-IDF, etc using pipelines. 

Craig

**Comment by ArvinZhuang** [comment]
Our course starts next week! but I believe there will be 2 to 3 weeks of content before students reaching the point of writing their won weighting model.

**Comment by cmacdonald** [comment]
Hi. Sorry, due to my own teaching commitments in the next few weeks I cant develop, test and release this new feature in that timescale.

Some other possibilities:
1. Write the weighting model in Java, compile a jar file, and add that to PyTerrier classpath. A template class is available at https://github.com/cmacdonald/IRcourseHM/blob/master/src/main/java/uk/ac/gla/dcs/models/MyWeightingModel.java
2. Focus on re-rankers that can be expressed as pt.apply functions. 

See ECIR tutorial notebooks 1 &2 (https://github.com/terrier-org/ecir2021tutorial/tree/main/notebooks) for some examples

Craig

**Comment by ArvinZhuang** [comment]
Hi @cmacdonald , thanks for the suggestions! we will try to use pt.apply to re-rank boolean retrieval results, and also will try to let students manually iterate posting lists to compute doc scores.

**Comment by cmacdonald** [comment]
Hi all,

I have made a commit in a new branch that demonstrates this working: https://github.com/terrier-org/pyterrier/commit/b0378dd4d113698575cba1df64f7b642ff6d282d

You can see examples of 
(a) specifying a Java weighting model instance
https://github.com/terrier-org/pyterrier/blob/208python_wmodel/tests/test_br.py#L161
(b) specifying a weighting model entirely in Python:
https://github.com/terrier-org/pyterrier/blob/208python_wmodel/tests/test_br.py#L175

I need to test this a bit more in a few more situations, but I want to let you know that it is progressing.

Craig
