### ISSUE TITLE
pt.Experiment consistency in missing qids in topics/qrels/runs

### ISSUE THREAD

**Issue by cmacdonald** [terrier-org/pyterrier#226]
https://github.com/terrierteam/ir_measures/pull/17 changes the behaviour of ir_measures in the presence of qids that dont appear in the run but do appear in the qrels.

Some work is needed on pt.Experiment (and friends) to align with this change.

The general principle is that we should average in a safe manner.

There are different situations:

1. A qid is present in the topics and qrels, but not in the run - this topic should be given 0 score and therefore decrease the averaging. https://github.com/terrierteam/ir_measures/pull/17 does this for us.
2. A qid is present in the qrels, but not in the topics. 
  - ir_measures WILL count these qids during evaluation, as it does NOT have knowledge of the topics.
  - pt.Experiment should should ignore such topics during retrieval (by dropping them from the qrels), and ensure that they do not contribute to evaluation scores. 
3. A qid is present in the topics, but not in the qrels. Currently, pt.Experiment executes the topics, but does not count in evaluation. The `drop_unused` can be used to drop such topics. This is the status quo, and is unchanged.

This issue concerns the implementation of (2) above.

**Comment by cmacdonald** [comment]
As a strawman counter-example:

Consider evaluating a diversification use case. The topics are defined `"1", "2"` etc, but the qrels are defined at sub-topic level (and ir_measures knows how to deal with those), e.g. `"1-1", "1-2", "2-1"` etc

It would not be appropriate to simply ALWAYS do a left(?) outer join between topics and qrels.

So, it is proposed to add an option `filter_qrels`, which is set to True by default, but if the left outer join results in no results, then an Error should be omitted, which includes a hint that either the topics and qrels are disjoint, or  filter_qrels should be set to False.

**Comment by seanmacavaney** [comment]
An edge case: Right now, running `pt.Experiment` with and without `perquery` behave differently for qids that appear in topics but not in qrels:
 - `perquery=False`: these queries are not included in metric averages*
 - `perquery=True`: these queries appear with values of 0

Consequently, you could get different results if you ran with `perquery=False` vs if you ran `perquery=True` and averaged the numbers yourself.

As such, I think we should change the behaviour to one of the following:
 1. Do not include results for qids that appear in topics but not in qrels when `perquery=True`. Potentially show a warning in this case. Maybe this warning should appear even if `perquery=False`?
 2. Include results for qids that appear in topics but not qrels, but give them a special value (e.g., `NaN`) to indicate that they are different and force the user to filter them out before averaging.

@cmacdonald Do you have a preference on this? (Or stick with the current behaviour?)

\* The exception is `mrt`, which will include these values when averaging. Note that `mrt` is not given when `perquery=True`, presumably because an accurate per query measurement of runtime only makes sense with `batch_size=1`.

**Comment by cmacdonald** [comment]
How often do we think this occurs?
(2) NaN seems a credible answer for this scenario, as drop_unused would resolve most of the issue from the user side. A warning could be emitted?

**Comment by seanmacavaney** [comment]
I don't think it'd be terribly uncommon when `perquery=True` is used. Would only require `drop_unused=False` and a dataset that doesn't have judgments for all queries (e.g., TREC DL, TREC Robust).

(2) with a warning sounds good to me.
