### ISSUE TITLE
Coercion of other objects into transformers is dangerous

### ISSUE THREAD

**Issue by cmacdonald** [terrier-org/pyterrier#236]
**Is your feature request related to a problem? Please describe.**

Coercion of other objects into transformers can create unintended bugs. 

Two scenarios: 

1. Dataframe coercion

E.g.
```
pipe = br >> MyT(df)
```

Here MyT is already applied and created a dataframe, thus the pipeline is actually
```
pipe = br >> pt.transformer.SourceTransformer(df)
```

Users should instead be expected to make a transformer explicitly, e.g. by
`pt.as_source(df)?`
NB: This particular scenario has links with caching etc.

2. Function coercion

A common model is

```
def make_transformer(parameter) -> TransformerBase:
   return bla

pipe = br >> make_transformer
```
This is wrong, this is equivalent to 
```
pipe = br >> pt.apply.generic(make_transformer)
```
pt.apply.generic() should be used in favour of coercing function-like objects into transformers, as there are a number of different types of apply function, and selecting "generic" is arbitrary.

** Solution **
In general, coercion into transformers *in a pipeline* should be deprecated and a warning given

Coercion of dataframes into transformers within pt.Experiment() and friends is still thought as being acceptable.

**Comment by cmacdonald** [comment]
What should the function be that converts dataframes into transformers? Options:
  - `pt.coerce.df(df) -> SourceTransformer`
  - `pt.as_source(df)-> SourceTransformer`

**Comment by seanmacavaney** [comment]
Per offline discussion with @cmacdonald:

Neither of the above are nice because it's not immediately obvious what they do. We considered a bunch of options (see below), but landed on:
 - Alias `TransformerBase` to `Transformer` under pt. (Eventually deprecate TransformerBase?)
 - `pt.Transformer.from_df() -> SourceTransformer`
 - Also add operators there, such as `pt.Transformer.linear(), .then(), .union(), .itersect(), .cutoff()` as alternatives to the operator syntax.

Other options considered that we didn't really like: `pt.dataframe_to_transformer, pt.convert.to_transformer, pt.transformer.wrap, pt.transformer.wrap_df, pt.Transformer(df)`

**Comment by cmacdonald** [comment]
Now addressed :-)

> Also add operators there, such as pt.Transformer.linear(), .then(), .union(), .itersect(), .cutoff() as alternatives to the operator syntax.

Not so sure about these - we can continue to discuss.
