### ISSUE TITLE
non-string Properties not being correctly set on BatchRetrieve

### ISSUE THREAD

**Issue by ArthurCamara** [terrier-org/pyterrier#27]
I'm probably missing something, but the `properties` dict is not being correctly set when instantiating a `BatchRetrieve` object:

```
retriever = pt.BatchRetrieve(index, {"wmodel":"BM25"}, properties = {"verbose": True, "matching.retrieved_set_size": 100})
len(retriever.transform("hello world 2")) == 100
> False
```

**Comment by cmacdonald** [comment]
`controls = {"end" : "9"}` should do what you want.

Or

```
retriever = pt.BatchRetrieve(index, {"wmodel":"BM25"} % 100
```

**Comment by ArthurCamara** [comment]
Do we have documentation on what are the accepted properties?

**Comment by cmacdonald** [comment]
Currently, those properties should solely refer to Terrier. Most are documented in the Javadoc, or in the documentation. I took away that particular properties page, as it was outdated.

In Terrier, I'm moving away from properties in general (globals are bad); They are being replaced by commandline options, and controls.

`matching.retrieved_set_size` should work as a property. The problem is that if you have two BatchRetrieve instances, both would be affected by the setting of `matching.retrieved_set_size` in one instance. See #10

```pt.BatchRetrieve(index, {"wmodel":"BM25"}) % 100``` is intended to the Pyterrier way. It could be rewritten internally to push the 100 into the BatchRetrieve instance, once #10 is fixed. #10 requires something to change in Terrier. 

All that said, in an scenario with only one BatchRetrieve instance, your test case should work, so I will check that.

**Comment by ArthurCamara** [comment]
That makes sense. I agree that globals should be avoided.
Nevertheless, a single doc page (either here or in terrier-core) with all possible keys for `control` is an interesting thing to do.

**Comment by cmacdonald** [comment]
>  I agree that globals should be avoided.
Dont we know that!

>Nevertheless, a single doc page (either here or in terrier-core) with all possible keys for control is an interesting thing to do.
Noted, I'll make a Terrier issue.

**Comment by cmacdonald** [comment]
Hi Arthur,

I checked this:

`retriever = pt.BatchRetrieve(index, {"wmodel":"BM25"}, properties = {"matching.retrieved_set_size": 100})`
wouldnt work, but 
`retriever = pt.BatchRetrieve(index, {"wmodel":"BM25"}, properties = {"matching.retrieved_set_size": "100"})`
does.

There is an underlying problem with jnius, which I can report, but I am committing a patch for Pyterrier.

I also created a controls documentation page, as requested:
https://github.com/terrier-org/terrier-core/blob/5.x/doc/configure_retrieval_controls.md
