### ISSUE TITLE
pt.init() for nptyping v2.0.0 gives an error

### ISSUE THREAD

**Issue by tabonnet** [terrier-org/pyterrier#290]
Hi Dr MacDonald. I just emailed you about this but I thought I'd raise the issue here too. pt.init() is throwing an error and the modules aren't working. This wasn't happening the last time I was using PyTerrier a few weeks ago.

![image](https://user-images.githubusercontent.com/32340929/162605124-8e04f37c-f89e-472f-8ee2-249d882d8522.png)

Best wishes,

Tyler

**Comment by cmacdonald** [comment]
I think nptyping has made a new release and it’s broken something. Can you try installing nptyping 1.4.4.

If that works I’ll do a 0.8 release shortly to peg the version

Craig

[cid:DFB1D250-6277-45FA-8884-4CF4D0432C0E][cid:9841FA50-3931-41DB-A8CB-F023E225876D]

Sent from my iPhone

On 10 Apr 2022, at 08:18, tabonnet ***@***.***> wrote:

﻿

Hi Dr MacDonald. I just emailed you about this but I thought I'd raise the issue here too. pt.init() is throwing an error and the modules aren't working. This wasn't happening the last time I was using PyTerrier a few weeks ago.

[image]<https://user-images.githubusercontent.com/32340929/162605124-8e04f37c-f89e-472f-8ee2-249d882d8522.png>

Best wishes,

Tyler

**Comment by tabonnet** [comment]
Okay, installation worked.

![image](https://user-images.githubusercontent.com/32340929/162607811-42d78e65-0ac9-4c7a-b5d6-82ee177b15d6.png)

**Comment by cmacdonald** [comment]
You need to tag the version number `pip install nptyping==1.4.4.`

**Comment by tabonnet** [comment]
Oh right of course. Yes it works.

![image](https://user-images.githubusercontent.com/32340929/162607941-e02f6674-e5d3-4cfa-8c50-142d48e973cb.png)

**Comment by cmacdonald** [comment]
And that solves the pt.init() error, right?

if so, I will push a new release of PyTerrier in the next hour

**Comment by tabonnet** [comment]
Yes it solves it. Thanks!

![image](https://user-images.githubusercontent.com/32340929/162608343-6cbdd612-1b85-4c05-abb3-6cf770e1ca34.png)

**Comment by cmacdonald** [comment]
Unit tests show that pegging to 1.4.4 fixes the problem. Breaking API change reported upstream to https://github.com/ramonhagenaars/nptyping/issues/62

**Comment by cmacdonald** [comment]
PyTerrier 0.8.1 now released which fixes the nptyping version. Thanks for the report!
