### ISSUE TITLE
Warning when indexing

### ISSUE THREAD

**Issue by yanyu9385** [terrier-org/pyterrier#311]
Could you please tell me that, under what circumstances is an empty document usually created automatically for me when creating an index?
For example, "[main] WARN org.terrier.structures.indexing.Indexer - Adding an empty document to the index (123) - further warnings are suppressed".
Further more, I have checked that this document ID has content.
Thank you very much.

**Comment by seanmacavaney** [comment]
Hi @yanyu9385,

You'll get that warning when the term pipeline gives no tokens, which, by default, can be in several cases. E.g., these are several that I can think of off the top of my head:

```python
# Document is empty
>>> idx = pt.index.IterDictIndexer('./test1')
>>> idx.index([{'docno': '1', 'text': ''}])
WARN org.terrier.structures.indexing.Indexer - Adding an empty document to the index (1) - further warnings are suppressed

# only whitespace
>>> idx = pt.index.IterDictIndexer('./test2')
>>> idx.index([{'docno': '1', 'text': '        '}])
WARN org.terrier.structures.indexing.Indexer - Adding an empty document to the index (1) - further warnings are suppressed

# only stopwords
>>> idx = pt.index.IterDictIndexer('./test3')
>>> idx.index([{'docno': '1', 'text': 'the a but and'}])
WARN org.terrier.structures.indexing.Indexer - Adding an empty document to the index (1) - further warnings are suppressed

# only punctuation
>>> idx = pt.index.IterDictIndexer('./test4')
>>> idx.index([{'docno': '1', 'text': '.!?'}]) # only utf characters
WARN org.terrier.structures.indexing.Indexer - Adding an empty document to the index (1) - further warnings are suppressed

# only UTF characters (which are removed by default)
>>> idx = pt.index.IterDictIndexer('./test5')
>>> idx.index([{'docno': '1', 'text': 'ü'}])
WARN org.terrier.structures.indexing.Indexer - Adding an empty document to the index (1) - further warnings are suppressed
```

I suspect that since you said there was content, your case may be the last one, with UTF characters? If so, you may want to do this, and check out [the notebook on non-English indexing/retrieval](https://github.com/terrier-org/pyterrier/blob/master/examples/notebooks/non_en_retrieval.ipynb):

```python
idx.setProperty("tokeniser", "UTFTokeniser") # Replaces the default EnglishTokeniser, which makes assumptions specific to English
idx.setProperty("termpipelines", "") # Removes the default PorterStemmer (English)
```

Changing the term pipelines can address most of the other situations, but exactly what to change depends on your desired behaviour.

Does this help?

**Comment by yanyu9385** [comment]
Hi @seanmacavaney , thank you for your reply, the solution you provided solved my problem perfectly, thanks again!
