### ISSUE TITLE
[Question] Confusion regarding the matchop flag when using custom tokenizer

### ISSUE THREAD

**Issue by T-Almeida** [terrier-org/pyterrier#365]
Hi,

As the title suggests, I am a bit confused regarding the inner workings of the matchop flag when doing a search with a custom tokenizer, consider the following [pyterrier docs](https://pyterrier.readthedocs.io/en/latest/terrier-indexing.html#pretokenised) for more context. 

In my case, I have a simple tokenizer that accepts any alphanumeric character plus the "-" hyphen. The index part was pretty straightforward, where I directly feed the token counts to the indexer (This is very intuitive). However, the retrieval phase becomes a bit confusing. As far as I understood, we need to use the `pt.rewrite.tokenise` with `matchop=True` to avoid the `Terrier’s tokeniser`, which at least for me sounds like a bit of magic, since I did not see any further explanation. This raises a bit of uncertainty about what I am doing since I no longer know if what I am doing is correct.

For instance, if I run the following question `What is the self-attention?` with `matchop=True` I would get the query `what is the #base64(c2VsZi1hdHRlbnRpb24=)`. I understand that the "-" character is not a valid `string. ascii_letters` or `string.digit` and therefore will be encoded, but I fail to understand what happens next in the retrieval? The #base64(c2VsZi1hdHRlbnRpb24=) will be decoded before the retrieval algorithm? So when Terrier is doing the search it will use the terms ["what", "is", "the", "self-attention"]? On the other hand, if I set `matchop=False` the resulting query is `what is the self-attention`, however, the term self-attention seems to be ignored by the retrieval engine. 

I made a [colab](https://colab.research.google.com/drive/1BRg8cuODeoPpkx5Jk0LMcyW5heOVxtWh?usp=sharing) with some examples, that gave me the intuition to believe that using the `matchop=True` is the correct way of running. I also think that my confusion came when I look at the results dataframe and I saw that the query text had that strange encoding: 

```python
  | qid | docid | docno | rank | score | query_0 | query
-- | -- | -- | -- | -- | -- | -- | --
0 | 0 | 0 | 0 | 1.851500 | What is the self-attention? | what is the #base64(c2VsZi1hdHRlbnRpb24=)
0 | 1 | 1 | 1 | 1.592436 | What is the self-attention? | what is the #base64(c2VsZi1hdHRlbnRpb24=)

```

Thanks in advance.

**Comment by cmacdonald** [comment]
Hi @T-Almeida - thanks for the detailed question, and apologies for the delayed response.

If matchop is used, then yes, it avoids Terrier's tokeniser. The term should be taken verbatim into the retrieval process.

You can see how matchop is handled here:
https://github.com/terrier-org/terrier-core/blob/5.x/modules/core/src/main/javacc/matchopql/MatchOpQLParser.jj#L379-L393
Its assumed to be a single-term word, that has unparsable characters. 

MatchOp query language in Terrier is a subset of the Indri query language, and is documented at https://github.com/terrier-org/terrier-core/blob/5.x/doc/querylanguage.md#matching-op-query-language

Some pieces of advice:
 - double check, by inspecting the data.properties for the index that the termpipeline is indeed empty for the generated index.
 - you can use Tf weighting model rather than the default DPH for scoring to allow you to see what is being counted in each document.

HTH

BTW: Only terrier will understand the matchop query language - other backends in Pyterrier will not...
