### ISSUE TITLE
cgi replacement for modern version of python

### ISSUE THREAD

**Issue by Seln12** [terrier-org/pyterrier#509]
**Is your feature request related to a problem? Please describe.**
facing a problem with the deprecated cgi module. 
**Describe the solution you'd like**
can you release a version of the library that removes cgi and replaces it with a modern solution.
**Describe alternatives you've considered**
**Additional context**

**Comment by seanmacavaney** [comment]
Hi @Seln12 -- I can't seem to find where `cgi` is used by this package or its dependencies.

Perhaps the issue is meant for https://github.com/dfurtado/pyterrier instead?

(If you're looking to use the IR platform instead of the web framework, you'll want to `pip install python-terrier` instead of `pip install pyterrier`.)

**Comment by Seln12** [comment]
Thank you very much for your reply, I find it out lately that I was pip
installing pyterrier only.

Best regards

**Comment by seanmacavaney** [comment]
No problem, just let us know if you encounter anything else :)

**Comment by Seln12** [comment]
Thank you and I will.

**Comment by Seln12** [comment]
Good morning

Can I ask also how can I fix this one . Attached. A file below

Thanks in advance ,

**Comment by cmacdonald** [comment]
no attachment?
